## backgrounds.rpy
## Scales all background images to exactly fill the 1280×720 screen.

image bg_venable_home          = im.Scale("images/bg_venable_home.png",          1280, 720)
image bg_land_run              = im.Scale("images/bg_land_run.png",              1280, 720)
image bg_land_run_ch1          = im.Scale("images/bg_land_run_ch1.png",          1280, 720)
image bg_wagon_trail           = im.Scale("images/bg_wagon_trail.png",           1280, 720)
image bg_osage_tent_town       = im.Scale("images/bg_osage_tent_town.png",       1280, 720)
image bg_wigwam_office         = im.Scale("images/bg_wigwam_office.png",         1280, 720)
image bg_journal               = im.Scale("images/bg_journal.png",               1280, 720)
image bg_tent_church           = im.Scale("images/bg_tent_church.png",           1280, 720)
image bg_cravat_home           = im.Scale("images/bg_cravat_home.png",           1280, 720)
image bg_osage_parlor          = im.Scale("images/bg_osage_parlor.png",          1280, 720)
image bg_wigwam_office_daytime = im.Scale("images/bg_wigwam_office_daytime.png", 1280, 720)
image bg_osage_street_1895     = im.Scale("images/bg_osage_street_1895.png",     1280, 720)
image bg_hefner_window         = im.Scale("images/bg_hefner_window.png",         1280, 720)
image bg_editorial_office_night= im.Scale("images/bg_editorial_office_night.png",1280, 720)
image bg_osage_street_1900     = im.Scale("images/bg_osage_street_1900.png",     1280, 720)
image bg_courthouse_interior   = im.Scale("images/bg_courthouse_interior.png",   1280, 720)
image bg_civic_hall            = im.Scale("images/bg_civic_hall.png",            1280, 720)
image bg_oil_derrick_distant   = im.Scale("images/bg_oil_derrick_distant.png",   1280, 720)
image bg_wigwam_modern         = im.Scale("images/bg_wigwam_modern.png",         1280, 720)
image bg_kihekah_house_parlor  = im.Scale("images/bg_kihekah_house_parlor.png",  1280, 720)
image bg_cravat_kitchen        = im.Scale("images/bg_cravat_kitchen.png",        1280, 720)
image bg_wazhazhe_bungalow     = im.Scale("images/bg_wazhazhe_bungalow.png",     1280, 720)
image bg_washington_dc_hall    = im.Scale("images/bg_washington_dc_hall.png",    1280, 720)
image bg_oil_field_bowlegs     = im.Scale("images/bg_oil_field_bowlegs.png",     1280, 720)
image bg_monument_ceremony     = im.Scale("images/bg_monument_ceremony.png",     1280, 720)
